name    'ft-binary_writer'
version '${project.version}'
source 'UNKNOWN'
author 'ft'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'ft/content_runnablejar', '1.x.x'
dependency 'ft/common_pp_up', '>=0.0.1'